name: Node.js CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - run: npm install
    - run: npm version patch
    - run: git config user.email "calcagni.gabriel86@gmail.com"
    - run: git config user.name "solidsnk86"
    - run: git push
    - run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
