name: Node.js CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 'latest'
        registry-url: 'https://registry.npmjs.org'

    - name: Configure Git
      run: |
        git config --global user.email "calcagni.gabriel86@gmail.com"
        git config --global user.name "solidsnk86"

    - name: Install dependencies
      run: npm install

    - name: Commit package-lock.json if changed
      run: |
        git add package-lock.json
        git commit -m "chore: update package-lock.json" || true

    - name: Version and publish
      run: |
        git status
        npm version patch --force
        git push --follow-tags
        npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
